services:
  db:
    image: postgres:12
    environment:
      PGDATA: /data/pgdata
      POSTGRES_DB: jambo
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/data/pgdata

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_ENV: docker
      CSRF_TRUSTED_ORIGINS:
      CORS_ORIGIN_WHITELIST:
    env_file:
      - .env
    volumes:
      - static:/static

  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - backend

  docs:
    build:
      context: ./docs
    ports:
      - "5173:5173"

volumes:
  static:
  db_data: