services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static:/static

  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - backend

  docs:
    build:
      context: ./docs
    ports:
      - "5173:5173"

volumes:
  static: